apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: tooling
  name: personal-site-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  tls:
    - secretName: traefik-cert
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: personal-site
          servicePort: 80